#Exception


#program to raise an exception

try:
    num = int(input("Please enter number: "))
    print("num = ",num)
except ValueError:
    print("wrong value")
    
#program to raise an exception given that rollno. is valid if it is in the rande of (1-120)

try:
    num=int(input("enter roll number:"))
    if (num > 120 or num < 1):
        raise exception
    else:
        print("correct roll number")
    print("number=",num)
except:
    print("wrong value")


#program to input number from user raise an exception if it is invalid use finally to print end of the program

try:
    n=int(input("enter numeric value:"))
    print("you have entered correct value")
except:
    print("you have entered wrong value")
else:
    print("there is no exception")
finally:
    print("end of the program")


#program to emplement user defined exception

class userdefinedException(Exception):
    def __init__(self,msg):
        self.message=msg
try:
    n=int(input("enter numeric value:"))
    if (n>120 or n<-1):
        raise userdefinedException("incorrect roll number")
    else:
        print("you have entered correct value")
except userdefinedException as u:
    print(u.message)

    
    
